# Generated by Django 6.0.4 on 2026-04-08 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable cluster label, e.g. 'Campaign-XMP-abc123'", max_length=200)),
                ('repr_sha256', models.CharField(blank=True, help_text='Representative file hash for this cluster', max_length=64)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clusters',
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('original_name', models.CharField(max_length=255)),
                ('mime', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='Size in bytes')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed_parse', 'Failed — Parse'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('quarantine_path', models.CharField(help_text='Path inside QUARANTINE_DIR', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_json', models.JSONField(default=dict, help_text='All extracted features as a JSON object')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='analysis.file')),
            ],
            options={
                'db_table': 'features',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ml_label', models.CharField(blank=True, default='', max_length=30)),
                ('ml_score', models.FloatField(default=0.0)),
                ('vt_summary_json', models.JSONField(default=dict, help_text='VirusTotal enrichment snapshot: detections, first/last seen')),
                ('banner', models.CharField(choices=[('clean', 'Clean'), ('suspicious', 'Suspicious'), ('malicious', 'Malicious'), ('needs_review', 'Needs Review')], default='needs_review', max_length=20)),
                ('top_features', models.JSONField(default=list, help_text='Top contributing features for explainability')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='analysis.cluster')),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='analysis.file')),
            ],
            options={
                'db_table': 'results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YaraHit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_name', models.CharField(max_length=200)),
                ('details', models.JSONField(default=dict, help_text='Match details: tags, byte offsets, severity, description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yara_hits', to='analysis.file')),
            ],
            options={
                'db_table': 'yara_hits',
                'ordering': ['-created_at'],
            },
        ),
    ]
