# Generated by Django 6.0.4 on 2026-04-08 10:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKeyConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(help_text='e.g. virustotal', max_length=100, unique=True)),
                ('key_hash', models.CharField(help_text='Hashed or encrypted API key (never plaintext in DB)', max_length=200)),
                ('status', models.CharField(default='active', max_length=20)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('last_rotated', models.DateTimeField(auto_now=True)),
                ('configured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configured_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_key_configs',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('auth', 'Authentication'), ('upload', 'File Upload'), ('analysis', 'Analysis'), ('config', 'Configuration Change'), ('admin', 'Admin Action')], max_length=20)),
                ('action', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details_json', models.JSONField(default=dict, help_text='Extra context: file hash, rule name, error message, etc.')),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log entry',
                'verbose_name_plural': 'audit log entries',
                'db_table': 'audit',
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='MLModelVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('model_file', models.FileField(upload_to='models/')),
                ('is_active', models.BooleanField(default=False, help_text='Only one version should be active at a time')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_models', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_model_versions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='YaraRuleSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('rule_file', models.FileField(upload_to='yara_rules/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'yara_rule_sets',
                'ordering': ['-updated_at'],
            },
        ),
    ]
